name: varlociraptor-dev
channels:
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  - alignoth
  - bcftools
  - bwa
  - bzip2
  - ca-certificates
  - cmake
  - curl
  - expat
  - gcc
  - gsl
  - htslib
  - make
  - mason
  - perl
  - pkg-config
  - samtools
  - xz
  - zlib
  - zlib-ng
  - zstd
  - clangdev
